<?php

namespace AppBundle\Repository;

/**
 * PocketUrlRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PocketUrlRepository extends \Doctrine\ORM\EntityRepository
{
}
